### ISSUE TITLE
selfupdate problem with version 1.0.0.46

### ISSUE THREAD

**Issue by araguan** [vigoo/bari#122]
```
Unhandled Exception: System.Diagnostics.Contracts.__ContractsRuntime+ContractException: Precondition failed.
   at Bari.Core.Generic.FileSystemDirectoryExtensions.GetChildDirectory(IFileSystemDirectory root, String childName, Boolean createIfMissing)
   at Bari.Console.Program.Main(String[] args)
```

**Comment by vigoo** [comment]
Yes I know, the latest improvement (default target support) broke it :(
Please use 1.0.0.45 until it is fixed.
