### ISSUE TITLE
SerializationException has been thrown during test

### ISSUE THREAD

**Issue by tgaboka** [vigoo/bari#132]
```
ERROR - Failed to run builder 196ee56b6777e1bcf8b4cdac4e08ce9a: System.Runtime.Serialization.SerializationException: The internal array cannot expand to greater than Int32.MaxValue elements.
   at System.Runtime.Serialization.ObjectIDGenerator.Rehash()
   at System.Runtime.Serialization.ObjectIDGenerator.GetId(Object obj, Boolean& firstTime)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(Object obj, Boolean assignUniqueIdToValueType, Type type, Boolean& isNew)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Schedule(Object obj, Boolean assignUniqueIdToValueType, Type type, WriteObjectInfo objectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers(NameInfo memberNameInfo, NameInfo memberTypeNameInfo, Object memberData, WriteObjectInfo objectInfo, NameInfo typeNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, String memberName, Type memberType, Object memberData, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, String[] memberNames, Type[] memberTypes, Object[] memberData, WriteObjectInfo[] memberObjectInfos)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, Object data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Bari.Core.Build.Dependencies.Protocol.BinarySerializer.Serialize[T](Stream stream, T obj)
   at Bari.Core.Build.Cache.FileBuildCache.SaveDependencyFingerprint(IDependencyFingerprint fingerprint, IFileSystemDirectory cacheDir)
   at Bari.Core.Build.Cache.FileBuildCache.Store(BuildKey builder, IDependencyFingerprint fingerprint, IEnumerable`1 outputs, IFileSystemDirectory targetRoot)
   at Bari.Core.Build.Cache.CachedBuilder.Run(IBuildContext context)
DEBUG - Using hash based sln name: 196ee56b6777e1bcf8b4cdac4e08ce9a
System.Runtime.Serialization.SerializationException: The internal array cannot expand to greater than Int32.MaxValue elements.
   at System.Runtime.Serialization.ObjectIDGenerator.Rehash()
   at System.Runtime.Serialization.ObjectIDGenerator.GetId(Object obj, Boolean& firstTime)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(Object obj, Boolean assignUniqueIdToValueType, Type type, Boolean& isNew)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Schedule(Object obj, Boolean assignUniqueIdToValueType, Type type, WriteObjectInfo objectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMembers(NameInfo memberNameInfo, NameInfo memberTypeNameInfo, Object memberData, WriteObjectInfo objectInfo, NameInfo typeNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteMemberSetup(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, String memberName, Type memberType, Object memberData, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo, String[] memberNames, Type[] memberTypes, Object[] memberData, WriteObjectInfo[] memberObjectInfos)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, Object data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Bari.Core.Build.Dependencies.Protocol.BinarySerializer.Serialize[T](Stream stream, T obj)
   at Bari.Core.Build.Cache.FileBuildCache.SaveDependencyFingerprint(IDependencyFingerprint fingerprint, IFileSystemDirectory cacheDir)
   at Bari.Core.Build.Cache.FileBuildCache.Store(BuildKey builder, IDependencyFingerprint fingerprint, IEnumerable`1 outputs, IFileSystemDirectory targetRoot)
   at Bari.Core.Build.Cache.CachedBuilder.Run(IBuildContext context)
   at Bari.Core.Build.Statistics.MonitoredBuilder.Run(IBuildContext context)
   at Bari.Core.Build.BuildContext.Run(IBuilder rootBuilder)
   at Bari.Core.Commands.Test.TestCommand.RunWithProjects(IEnumerable`1 projects, Boolean dumpMode)
   at Bari.Core.Commands.Test.TestCommand.Run(Suite suite, String[] parameters)
   at Bari.Console.Program.Main(String[] args)
```

**Comment by vigoo** [comment]
Probably fixed by https://github.com/vigoo/bari/pull/138, please verify

**Comment by Psychobilly87** [comment]
Verified!
