### ISSUE TITLE
Static Resource missing from builded dll

### ISSUE THREAD

**Issue by FireflyJani** [vigoo/bari#71]
Rebuild is good but if I modify a file and I do a build with bari the build is success but I got runtime error when I start the program.
If I comment out the `StaticResource` references the build is good.
There are another `StaticResource` too but only this is not good.

Provide value on `System.Windows.Markup.StaticResourceHolder` threw an exception.

```
{"Cannot find resource named 'M...ViewItemStyle'. Resource names are case sensitive."}

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at PCRPanel.InitializeComponent() in c:\Projects\target\tmp\...DP\PCRPanel.xaml:line 1
   at PCRPanel..ctor(IWrappedObjectFactory coreObjectFactory) in c:\Projects\src\...PCRPanel.xaml.cs:line 52
```

This is the missing style
```xml
<Style TargetType="{x:Type TreeViewElements:M...TreeViewItem}" x:Key="M...TreeViewItemStyle">
...
```

And we this like:
```xml
<Style x:Key="M...TvRootItemStyle" TargetType="{x:Type TreeViewElements:M...TreeViewItem}" BasedOn="{StaticResource M...TreeViewItemStyle}" >
```

**Comment by vigoo** [comment]
Not reproducible with latest builds.
